/* This file was generated by SableCC (http://www.sablecc.org/). */

package x_language.node;

import x_language.analysis.*;

@SuppressWarnings("nls")
public final class AArrayExt extends PArrayExt
{
    private PArrayExp _arrayExp_;

    public AArrayExt()
    {
        // Constructor
    }

    public AArrayExt(
        @SuppressWarnings("hiding") PArrayExp _arrayExp_)
    {
        // Constructor
        setArrayExp(_arrayExp_);

    }

    @Override
    public Object clone()
    {
        return new AArrayExt(
            cloneNode(this._arrayExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayExt(this);
    }

    public PArrayExp getArrayExp()
    {
        return this._arrayExp_;
    }

    public void setArrayExp(PArrayExp node)
    {
        if(this._arrayExp_ != null)
        {
            this._arrayExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arrayExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._arrayExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._arrayExp_ == child)
        {
            this._arrayExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._arrayExp_ == oldChild)
        {
            setArrayExp((PArrayExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
