/* This file was generated by SableCC (http://www.sablecc.org/). */

package x_language.node;

import x_language.analysis.*;

@SuppressWarnings("nls")
public final class AAssignArrayCompInitialize extends PInitialize
{
    private TId _id_;
    private PArrayComp _arrayComp_;

    public AAssignArrayCompInitialize()
    {
        // Constructor
    }

    public AAssignArrayCompInitialize(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PArrayComp _arrayComp_)
    {
        // Constructor
        setId(_id_);

        setArrayComp(_arrayComp_);

    }

    @Override
    public Object clone()
    {
        return new AAssignArrayCompInitialize(
            cloneNode(this._id_),
            cloneNode(this._arrayComp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignArrayCompInitialize(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PArrayComp getArrayComp()
    {
        return this._arrayComp_;
    }

    public void setArrayComp(PArrayComp node)
    {
        if(this._arrayComp_ != null)
        {
            this._arrayComp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arrayComp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._arrayComp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._arrayComp_ == child)
        {
            this._arrayComp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._arrayComp_ == oldChild)
        {
            setArrayComp((PArrayComp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
