/* This file was generated by SableCC (http://www.sablecc.org/). */

package x_language.node;

import x_language.analysis.*;

@SuppressWarnings("nls")
public final class AAssignIdCommand extends PCommand
{
    private TId _id_;
    private PAssignWithId _assignWithId_;

    public AAssignIdCommand()
    {
        // Constructor
    }

    public AAssignIdCommand(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PAssignWithId _assignWithId_)
    {
        // Constructor
        setId(_id_);

        setAssignWithId(_assignWithId_);

    }

    @Override
    public Object clone()
    {
        return new AAssignIdCommand(
            cloneNode(this._id_),
            cloneNode(this._assignWithId_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignIdCommand(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PAssignWithId getAssignWithId()
    {
        return this._assignWithId_;
    }

    public void setAssignWithId(PAssignWithId node)
    {
        if(this._assignWithId_ != null)
        {
            this._assignWithId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assignWithId_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._assignWithId_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._assignWithId_ == child)
        {
            this._assignWithId_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._assignWithId_ == oldChild)
        {
            setAssignWithId((PAssignWithId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
