/* This file was generated by SableCC (http://www.sablecc.org/). */

package x_language.node;

import x_language.analysis.*;

@SuppressWarnings("nls")
public final class AAssignConsAssign extends PConsAssign
{
    private PInitialize _initialize_;
    private PConsAssign _consAssign_;

    public AAssignConsAssign()
    {
        // Constructor
    }

    public AAssignConsAssign(
        @SuppressWarnings("hiding") PInitialize _initialize_,
        @SuppressWarnings("hiding") PConsAssign _consAssign_)
    {
        // Constructor
        setInitialize(_initialize_);

        setConsAssign(_consAssign_);

    }

    @Override
    public Object clone()
    {
        return new AAssignConsAssign(
            cloneNode(this._initialize_),
            cloneNode(this._consAssign_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignConsAssign(this);
    }

    public PInitialize getInitialize()
    {
        return this._initialize_;
    }

    public void setInitialize(PInitialize node)
    {
        if(this._initialize_ != null)
        {
            this._initialize_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._initialize_ = node;
    }

    public PConsAssign getConsAssign()
    {
        return this._consAssign_;
    }

    public void setConsAssign(PConsAssign node)
    {
        if(this._consAssign_ != null)
        {
            this._consAssign_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._consAssign_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._initialize_)
            + toString(this._consAssign_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._initialize_ == child)
        {
            this._initialize_ = null;
            return;
        }

        if(this._consAssign_ == child)
        {
            this._consAssign_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._initialize_ == oldChild)
        {
            setInitialize((PInitialize) newChild);
            return;
        }

        if(this._consAssign_ == oldChild)
        {
            setConsAssign((PConsAssign) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
