/* This file was generated by SableCC (http://www.sablecc.org/). */

package x_language.node;

import x_language.analysis.*;

@SuppressWarnings("nls")
public final class ABlockCommand extends PCommand
{
    private PBlockScope _blockScope_;

    public ABlockCommand()
    {
        // Constructor
    }

    public ABlockCommand(
        @SuppressWarnings("hiding") PBlockScope _blockScope_)
    {
        // Constructor
        setBlockScope(_blockScope_);

    }

    @Override
    public Object clone()
    {
        return new ABlockCommand(
            cloneNode(this._blockScope_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlockCommand(this);
    }

    public PBlockScope getBlockScope()
    {
        return this._blockScope_;
    }

    public void setBlockScope(PBlockScope node)
    {
        if(this._blockScope_ != null)
        {
            this._blockScope_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._blockScope_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._blockScope_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._blockScope_ == child)
        {
            this._blockScope_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._blockScope_ == oldChild)
        {
            setBlockScope((PBlockScope) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
