/* This file was generated by SableCC (http://www.sablecc.org/). */

package x_language.node;

import java.util.*;
import x_language.analysis.*;

@SuppressWarnings("nls")
public final class ABlockExp extends PExp
{
    private final LinkedList<PDecCons> _decCons_ = new LinkedList<PDecCons>();
    private final LinkedList<PExp> _exp_ = new LinkedList<PExp>();

    public ABlockExp()
    {
        // Constructor
    }

    public ABlockExp(
        @SuppressWarnings("hiding") List<?> _decCons_,
        @SuppressWarnings("hiding") List<?> _exp_)
    {
        // Constructor
        setDecCons(_decCons_);

        setExp(_exp_);

    }

    @Override
    public Object clone()
    {
        return new ABlockExp(
            cloneList(this._decCons_),
            cloneList(this._exp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlockExp(this);
    }

    public LinkedList<PDecCons> getDecCons()
    {
        return this._decCons_;
    }

    public void setDecCons(List<?> list)
    {
        for(PDecCons e : this._decCons_)
        {
            e.parent(null);
        }
        this._decCons_.clear();

        for(Object obj_e : list)
        {
            PDecCons e = (PDecCons) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._decCons_.add(e);
        }
    }

    public LinkedList<PExp> getExp()
    {
        return this._exp_;
    }

    public void setExp(List<?> list)
    {
        for(PExp e : this._exp_)
        {
            e.parent(null);
        }
        this._exp_.clear();

        for(Object obj_e : list)
        {
            PExp e = (PExp) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._exp_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decCons_)
            + toString(this._exp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decCons_.remove(child))
        {
            return;
        }

        if(this._exp_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PDecCons> i = this._decCons_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDecCons) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PExp> i = this._exp_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExp) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
