/* This file was generated by SableCC (http://www.sablecc.org/). */

package x_language.node;

import x_language.analysis.*;

@SuppressWarnings("nls")
public final class AConsAssign extends PConsAssign
{
    private PInitialize _initialize_;

    public AConsAssign()
    {
        // Constructor
    }

    public AConsAssign(
        @SuppressWarnings("hiding") PInitialize _initialize_)
    {
        // Constructor
        setInitialize(_initialize_);

    }

    @Override
    public Object clone()
    {
        return new AConsAssign(
            cloneNode(this._initialize_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConsAssign(this);
    }

    public PInitialize getInitialize()
    {
        return this._initialize_;
    }

    public void setInitialize(PInitialize node)
    {
        if(this._initialize_ != null)
        {
            this._initialize_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._initialize_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._initialize_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._initialize_ == child)
        {
            this._initialize_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._initialize_ == oldChild)
        {
            setInitialize((PInitialize) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
