/* This file was generated by SableCC (http://www.sablecc.org/). */

package x_language.node;

import x_language.analysis.*;

@SuppressWarnings("nls")
public final class ACreateDecVar extends PDecVar
{
    private PType _type_;
    private PMultDecVar _multDecVar_;

    public ACreateDecVar()
    {
        // Constructor
    }

    public ACreateDecVar(
        @SuppressWarnings("hiding") PType _type_,
        @SuppressWarnings("hiding") PMultDecVar _multDecVar_)
    {
        // Constructor
        setType(_type_);

        setMultDecVar(_multDecVar_);

    }

    @Override
    public Object clone()
    {
        return new ACreateDecVar(
            cloneNode(this._type_),
            cloneNode(this._multDecVar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACreateDecVar(this);
    }

    public PType getType()
    {
        return this._type_;
    }

    public void setType(PType node)
    {
        if(this._type_ != null)
        {
            this._type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._type_ = node;
    }

    public PMultDecVar getMultDecVar()
    {
        return this._multDecVar_;
    }

    public void setMultDecVar(PMultDecVar node)
    {
        if(this._multDecVar_ != null)
        {
            this._multDecVar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multDecVar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._type_)
            + toString(this._multDecVar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._type_ == child)
        {
            this._type_ = null;
            return;
        }

        if(this._multDecVar_ == child)
        {
            this._multDecVar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        if(this._multDecVar_ == oldChild)
        {
            setMultDecVar((PMultDecVar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
