/* This file was generated by SableCC (http://www.sablecc.org/). */

package x_language.node;

import x_language.analysis.*;

@SuppressWarnings("nls")
public final class ADecConsBlockScope extends PBlockScope
{
    private PDecCons _decCons_;

    public ADecConsBlockScope()
    {
        // Constructor
    }

    public ADecConsBlockScope(
        @SuppressWarnings("hiding") PDecCons _decCons_)
    {
        // Constructor
        setDecCons(_decCons_);

    }

    @Override
    public Object clone()
    {
        return new ADecConsBlockScope(
            cloneNode(this._decCons_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecConsBlockScope(this);
    }

    public PDecCons getDecCons()
    {
        return this._decCons_;
    }

    public void setDecCons(PDecCons node)
    {
        if(this._decCons_ != null)
        {
            this._decCons_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decCons_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decCons_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decCons_ == child)
        {
            this._decCons_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._decCons_ == oldChild)
        {
            setDecCons((PDecCons) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
