/* This file was generated by SableCC (http://www.sablecc.org/). */

package x_language.node;

import x_language.analysis.*;

@SuppressWarnings("nls")
public final class ADecProcedureStart extends PStart
{
    private PDecProcedure _decProcedure_;

    public ADecProcedureStart()
    {
        // Constructor
    }

    public ADecProcedureStart(
        @SuppressWarnings("hiding") PDecProcedure _decProcedure_)
    {
        // Constructor
        setDecProcedure(_decProcedure_);

    }

    @Override
    public Object clone()
    {
        return new ADecProcedureStart(
            cloneNode(this._decProcedure_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecProcedureStart(this);
    }

    public PDecProcedure getDecProcedure()
    {
        return this._decProcedure_;
    }

    public void setDecProcedure(PDecProcedure node)
    {
        if(this._decProcedure_ != null)
        {
            this._decProcedure_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decProcedure_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decProcedure_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decProcedure_ == child)
        {
            this._decProcedure_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._decProcedure_ == oldChild)
        {
            setDecProcedure((PDecProcedure) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
