/* This file was generated by SableCC (http://www.sablecc.org/). */

package x_language.node;

import x_language.analysis.*;

@SuppressWarnings("nls")
public final class ADecCons extends PDecCons
{
    private PType _type_;
    private PConsAssign _consAssign_;

    public ADecCons()
    {
        // Constructor
    }

    public ADecCons(
        @SuppressWarnings("hiding") PType _type_,
        @SuppressWarnings("hiding") PConsAssign _consAssign_)
    {
        // Constructor
        setType(_type_);

        setConsAssign(_consAssign_);

    }

    @Override
    public Object clone()
    {
        return new ADecCons(
            cloneNode(this._type_),
            cloneNode(this._consAssign_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecCons(this);
    }

    public PType getType()
    {
        return this._type_;
    }

    public void setType(PType node)
    {
        if(this._type_ != null)
        {
            this._type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._type_ = node;
    }

    public PConsAssign getConsAssign()
    {
        return this._consAssign_;
    }

    public void setConsAssign(PConsAssign node)
    {
        if(this._consAssign_ != null)
        {
            this._consAssign_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._consAssign_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._type_)
            + toString(this._consAssign_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._type_ == child)
        {
            this._type_ = null;
            return;
        }

        if(this._consAssign_ == child)
        {
            this._consAssign_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        if(this._consAssign_ == oldChild)
        {
            setConsAssign((PConsAssign) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
