/* This file was generated by SableCC (http://www.sablecc.org/). */

package x_language.node;

import x_language.analysis.*;

@SuppressWarnings("nls")
public final class AEmptyParameters extends PParameters
{

    public AEmptyParameters()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AEmptyParameters();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEmptyParameters(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
