/* This file was generated by SableCC (http://www.sablecc.org/). */

package x_language.node;

import x_language.analysis.*;

@SuppressWarnings("nls")
public final class AFunctionCall extends PFunctionCall
{
    private TId _id_;
    private PListArgs _listArgs_;

    public AFunctionCall()
    {
        // Constructor
    }

    public AFunctionCall(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PListArgs _listArgs_)
    {
        // Constructor
        setId(_id_);

        setListArgs(_listArgs_);

    }

    @Override
    public Object clone()
    {
        return new AFunctionCall(
            cloneNode(this._id_),
            cloneNode(this._listArgs_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFunctionCall(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PListArgs getListArgs()
    {
        return this._listArgs_;
    }

    public void setListArgs(PListArgs node)
    {
        if(this._listArgs_ != null)
        {
            this._listArgs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listArgs_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._listArgs_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._listArgs_ == child)
        {
            this._listArgs_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._listArgs_ == oldChild)
        {
            setListArgs((PListArgs) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
