/* This file was generated by SableCC (http://www.sablecc.org/). */

package x_language.node;

import x_language.analysis.*;

@SuppressWarnings("nls")
public final class AIfElseCommandCommand extends PCommand
{
    private PIfElseCommand _ifElseCommand_;

    public AIfElseCommandCommand()
    {
        // Constructor
    }

    public AIfElseCommandCommand(
        @SuppressWarnings("hiding") PIfElseCommand _ifElseCommand_)
    {
        // Constructor
        setIfElseCommand(_ifElseCommand_);

    }

    @Override
    public Object clone()
    {
        return new AIfElseCommandCommand(
            cloneNode(this._ifElseCommand_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfElseCommandCommand(this);
    }

    public PIfElseCommand getIfElseCommand()
    {
        return this._ifElseCommand_;
    }

    public void setIfElseCommand(PIfElseCommand node)
    {
        if(this._ifElseCommand_ != null)
        {
            this._ifElseCommand_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ifElseCommand_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ifElseCommand_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ifElseCommand_ == child)
        {
            this._ifElseCommand_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ifElseCommand_ == oldChild)
        {
            setIfElseCommand((PIfElseCommand) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
