/* This file was generated by SableCC (http://www.sablecc.org/). */

package x_language.node;

import x_language.analysis.*;

@SuppressWarnings("nls")
public final class AMultiMultDecVar extends PMultDecVar
{
    private TId _id_;
    private PMultDecVar _multDecVar_;

    public AMultiMultDecVar()
    {
        // Constructor
    }

    public AMultiMultDecVar(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PMultDecVar _multDecVar_)
    {
        // Constructor
        setId(_id_);

        setMultDecVar(_multDecVar_);

    }

    @Override
    public Object clone()
    {
        return new AMultiMultDecVar(
            cloneNode(this._id_),
            cloneNode(this._multDecVar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiMultDecVar(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PMultDecVar getMultDecVar()
    {
        return this._multDecVar_;
    }

    public void setMultDecVar(PMultDecVar node)
    {
        if(this._multDecVar_ != null)
        {
            this._multDecVar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multDecVar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._multDecVar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._multDecVar_ == child)
        {
            this._multDecVar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._multDecVar_ == oldChild)
        {
            setMultDecVar((PMultDecVar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
