/* This file was generated by SableCC (http://www.sablecc.org/). */

package x_language.node;

import java.util.*;
import x_language.analysis.*;

@SuppressWarnings("nls")
public final class AStartProgram extends PProgram
{
    private final LinkedList<PStart> _start_ = new LinkedList<PStart>();

    public AStartProgram()
    {
        // Constructor
    }

    public AStartProgram(
        @SuppressWarnings("hiding") List<?> _start_)
    {
        // Constructor
        setStart(_start_);

    }

    @Override
    public Object clone()
    {
        return new AStartProgram(
            cloneList(this._start_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStartProgram(this);
    }

    public LinkedList<PStart> getStart()
    {
        return this._start_;
    }

    public void setStart(List<?> list)
    {
        for(PStart e : this._start_)
        {
            e.parent(null);
        }
        this._start_.clear();

        for(Object obj_e : list)
        {
            PStart e = (PStart) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._start_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._start_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._start_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PStart> i = this._start_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PStart) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
