/* This file was generated by SableCC (http://www.sablecc.org/). */

package x_language.node;

import x_language.analysis.*;

@SuppressWarnings("nls")
public final class TProcedure extends Token
{
    public TProcedure()
    {
        super.setText("procedure");
    }

    public TProcedure(int line, int pos)
    {
        super.setText("procedure");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TProcedure(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTProcedure(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TProcedure text.");
    }
}
