/* This file was generated by SableCC (http://www.sablecc.org/). */

package x_language.parser;

import x_language.node.*;
import x_language.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTReal(@SuppressWarnings("unused") TReal node)
    {
        this.index = 0;
    }

    @Override
    public void caseTInt(@SuppressWarnings("unused") TInt node)
    {
        this.index = 1;
    }

    @Override
    public void caseTBool(@SuppressWarnings("unused") TBool node)
    {
        this.index = 2;
    }

    @Override
    public void caseTIf(@SuppressWarnings("unused") TIf node)
    {
        this.index = 3;
    }

    @Override
    public void caseTThen(@SuppressWarnings("unused") TThen node)
    {
        this.index = 4;
    }

    @Override
    public void caseTElse(@SuppressWarnings("unused") TElse node)
    {
        this.index = 5;
    }

    @Override
    public void caseTWhile(@SuppressWarnings("unused") TWhile node)
    {
        this.index = 6;
    }

    @Override
    public void caseTProcedure(@SuppressWarnings("unused") TProcedure node)
    {
        this.index = 7;
    }

    @Override
    public void caseTFunction(@SuppressWarnings("unused") TFunction node)
    {
        this.index = 8;
    }

    @Override
    public void caseTCons(@SuppressWarnings("unused") TCons node)
    {
        this.index = 9;
    }

    @Override
    public void caseTVar(@SuppressWarnings("unused") TVar node)
    {
        this.index = 10;
    }

    @Override
    public void caseTPipe(@SuppressWarnings("unused") TPipe node)
    {
        this.index = 11;
    }

    @Override
    public void caseTLeftParen(@SuppressWarnings("unused") TLeftParen node)
    {
        this.index = 12;
    }

    @Override
    public void caseTRightParen(@SuppressWarnings("unused") TRightParen node)
    {
        this.index = 13;
    }

    @Override
    public void caseTLeftCurly(@SuppressWarnings("unused") TLeftCurly node)
    {
        this.index = 14;
    }

    @Override
    public void caseTRightCurly(@SuppressWarnings("unused") TRightCurly node)
    {
        this.index = 15;
    }

    @Override
    public void caseTLeftBrackets(@SuppressWarnings("unused") TLeftBrackets node)
    {
        this.index = 16;
    }

    @Override
    public void caseTRightBrackets(@SuppressWarnings("unused") TRightBrackets node)
    {
        this.index = 17;
    }

    @Override
    public void caseTAssign(@SuppressWarnings("unused") TAssign node)
    {
        this.index = 18;
    }

    @Override
    public void caseTSemicolon(@SuppressWarnings("unused") TSemicolon node)
    {
        this.index = 19;
    }

    @Override
    public void caseTComma(@SuppressWarnings("unused") TComma node)
    {
        this.index = 20;
    }

    @Override
    public void caseTAnd(@SuppressWarnings("unused") TAnd node)
    {
        this.index = 21;
    }

    @Override
    public void caseTOr(@SuppressWarnings("unused") TOr node)
    {
        this.index = 22;
    }

    @Override
    public void caseTNot(@SuppressWarnings("unused") TNot node)
    {
        this.index = 23;
    }

    @Override
    public void caseTPlus(@SuppressWarnings("unused") TPlus node)
    {
        this.index = 24;
    }

    @Override
    public void caseTMinus(@SuppressWarnings("unused") TMinus node)
    {
        this.index = 25;
    }

    @Override
    public void caseTDiv(@SuppressWarnings("unused") TDiv node)
    {
        this.index = 26;
    }

    @Override
    public void caseTMult(@SuppressWarnings("unused") TMult node)
    {
        this.index = 27;
    }

    @Override
    public void caseTMod(@SuppressWarnings("unused") TMod node)
    {
        this.index = 28;
    }

    @Override
    public void caseTGreater(@SuppressWarnings("unused") TGreater node)
    {
        this.index = 29;
    }

    @Override
    public void caseTSmaller(@SuppressWarnings("unused") TSmaller node)
    {
        this.index = 30;
    }

    @Override
    public void caseTEqual(@SuppressWarnings("unused") TEqual node)
    {
        this.index = 31;
    }

    @Override
    public void caseTSize(@SuppressWarnings("unused") TSize node)
    {
        this.index = 32;
    }

    @Override
    public void caseTPrint(@SuppressWarnings("unused") TPrint node)
    {
        this.index = 33;
    }

    @Override
    public void caseTRead(@SuppressWarnings("unused") TRead node)
    {
        this.index = 34;
    }

    @Override
    public void caseTInteger(@SuppressWarnings("unused") TInteger node)
    {
        this.index = 35;
    }

    @Override
    public void caseTRealNumber(@SuppressWarnings("unused") TRealNumber node)
    {
        this.index = 36;
    }

    @Override
    public void caseTBoolean(@SuppressWarnings("unused") TBoolean node)
    {
        this.index = 37;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 38;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 39;
    }
}
